name: Python Calculator

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Choose the Python version you want to use

    - name: Install dependencies
      run: pip install -r requirements.txt  # If you have any dependencies

    - name: Run Calculator
      run: python calculator.py  # Replace 'calculator.py' with the name of your Python calculator script
